### PR TITLE
contract of cognition

### PR DESCRIPTION
**Pull request by pfichtner**
Please accept the PR after
- [pact](https://github.com/pact-foundation/pact-python) is integrated
- the test was red (failing)
- the test became green

### CODE REVIEW

**Comment by pfichtner** [comment]
@KingMus What about detection's pact support?

**Comment by pfichtner** [comment]
@KingMus What about detection's pact support?

**Comment by KingMus** [comment]
On it :+1:

**Comment by KingMus** [comment]
Still not done.

**Comment by pfichtner** [comment]
@KingMus Still on it? :-/

**Comment by pfichtner** [comment]
:-/

**Pull request closed without merging**
